version: 2.1

orbs:
  rdwv: rdwv/rdwv-shared@2

jobs:
  test:
    executor: rdwv/docker-python

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            cd generator
            pip install -r requirements.txt
            pip install -r test-requirements.txt

      - run:
          name: run tests
          command: |
            make ci

      - rdwv/codecov:
          args: ""

  cansetup:
    executor: rdwv/build-ubuntu
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Test installation
          command: |
            cd .circleci
            sudo ./test-install.sh

  deploy:
    executor: rdwv/build-ubuntu

    environment:
      BUILD_PLATFORMS: linux/amd64,linux/arm64/v8

    working_directory: ~/repo

    steps:
      - checkout
      - rdwv/login-to-registries
      - rdwv/enable-buildx
      - run:
          name: build docker image
          command: |
            cd generator
            docker buildx build --progress plain --push --platform ${BUILD_PLATFORMS} --tag rdwv/docker-compose-generator:latest \
            --tag ghcr.io/rdwv/docker-compose-generator:latest .

workflows:
  version: 2
  build:
    jobs:
      - rdwv/lint:
          name: lint
          executor: rdwv/build-ubuntu
      - test:
          requires:
            - lint
      - cansetup:
          requires:
            - test
      - deploy:
          context: global
          requires:
            - cansetup
          filters:
            branches:
              only: master
