services:
  store:
    restart: unless-stopped
    image: rdwv/rdwv-store:stable
    expose:
      - "3000"
    command: yarn start
    environment:
      RDWV_STORE_API_URL: ${RDWV_STORE_API_URL}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ${RDWV_STORE_HOST}
      VIRTUAL_HOST_NAME: "rdwv-store"
      LETSENCRYPT_HOST: ${RDWV_STORE_HOST}
      LETSENCRYPT_EMAIL: ${RDWV_LETSENCRYPT_EMAIL}
      RDWV_STORE_ROOTPATH: ${RDWV_STORE_ROOTPATH:-/}
      RDWV_ADMIN_HOST: ${RDWV_ADMIN_HOST}
      RDWV_ADMIN_ROOTPATH: ${RDWV_ADMIN_ROOTPATH:-/}
