services:
  worker:
    restart: unless-stopped
    image: rdwv/rdwv:stable
    command: python3 worker.py
    environment:
      LOG_FILE: rdwv.log
      RDWV_DATADIR: /datadir
      RDWV_BACKUPS_DIR: /backups
      RDWV_VOLUMES: /datadir /backups /plugins
      RDWV_CRYPTOS: ${RDWV_CRYPTOS:-btc}
      BTC_NETWORK: ${BTC_NETWORK:-mainnet}
      BTC_LIGHTNING: ${BTC_LIGHTNING:-false}
      BCH_NETWORK: ${BCH_NETWORK:-mainnet}
      ETH_NETWORK: ${ETH_NETWORK:-mainnet}
      BNB_NETWORK: ${BNB_NETWORK:-mainnet}
      SBCH_NETWORK: ${SBCH_NETWORK:-mainnet}
      MATIC_NETWORK: ${MATIC_NETWORK:-mainnet}
      TRX_NETWORK: ${TRX_NETWORK:-mainnet}
      XRG_NETWORK: ${XRG_NETWORK:-mainnet}
      LTC_NETWORK: ${LTC_NETWORK:-mainnet}
      LTC_LIGHTNING: ${LTC_LIGHTNING:-false}
      BSTY_NETWORK: ${BSTY_NETWORK:-mainnet}
      BSTY_LIGHTNING: ${BSTY_LIGHTNING:-false}
      GRS_NETWORK: ${GRS_NETWORK:-mainnet}
      GRS_LIGHTNING: ${GRS_LIGHTNING:-false}
      XMR_NETWORK: ${XMR_NETWORK:-mainnet}
      UPDATE_URL: ${RDWV_UPDATE_URL:-https://api.rdwv.ai/updates/latest}
      SSH_CONNECTION: "root@host.docker.internal:$<RDWV_SSH_PORT>:22?"
      SSH_KEY_FILE: ${RDWV_SSH_KEY_FILE}
      SSH_AUTHORIZED_KEYS: ${RDWV_SSH_AUTHORIZED_KEYS}
      BASH_PROFILE_SCRIPT: ${BASH_PROFILE_SCRIPT}
      RDWV_BACKEND_PLUGINS_DIR: /plugins/backend
      RDWV_ADMIN_PLUGINS_DIR: /plugins/admin
      RDWV_STORE_PLUGINS_DIR: /plugins/store
      RDWV_DOCKER_PLUGINS_DIR: /plugins/docker
      RDWV_HOST: ${RDWV_HOST}
      RDWV_ADMIN_HOST: ${RDWV_ADMIN_HOST}
      RDWV_ADMIN_ROOTPATH: ${RDWV_ADMIN_ROOTPATH:-/}
      RDWV_REVERSEPROXY: ${RDWV_REVERSEPROXY:-nginx-https}
      RDWV_HTTPS_ENABLED: ${RDWV_HTTPS_ENABLED:-false}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "9020"
    volumes:
      - "rdwv_datadir:/datadir"
      - "backup_datadir:/backups"
      - "./plugins/backend:/plugins/backend"
      - "./plugins/admin:/plugins/admin"
      - "./plugins/store:/plugins/store"
      - "./plugins/docker:/plugins/docker"
      - "$<RDWV_HOST_SSH_AUTHORIZED_KEYS>?:${RDWV_SSH_AUTHORIZED_KEYS}"

volumes:
  rdwv_datadir:
  backup_datadir:
    external: true
